name: Inspect Code with R++

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    name: Build

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Debug -A Win32

      - name: Inspect solution
        uses: muno92/resharper_inspectcode@1.11.12
        with:
          exclude: "**/external/**.*"
          failOnIssue: 0
          solutionPath: ${{github.workspace}}/build/among-us-replay-mod.sln
